apiVersion: v1
kind: Service
metadata:
  name: devops-enterprise-api-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: devops-enterprise-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080